# Setup
title:               hope
tagline:             'the sun always rises'
description:         ''
url:                 kvs56.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              krishnavaibhavsharma
  url:               https://kvs56.github.io
  email:             zeparselmouth@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.1
google_analytics_id: UA-146052-15
